spring:
  # DB 접속 정보 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://swbootcampdb.cw9l1vxm32yv.ap-northeast-2.rds.amazonaws.com:3306/session
    username: inha
    password: dlsgkeoghkdlxld**
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
