spring:
  # DB 접속 정보 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:localhost:3306/session
    username: root
    password: password
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
