/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _bootcamp_fec;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the '_bootcamp_fec.greeting' plugin.
 */
class 2023_BootCamp_FECPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("_bootcamp_fec.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
